name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Linux x86_64
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run:  |
        set -x
        cd src
        ./configure
        make -j
        file spaln | grep x86-64
        file makmdm | grep x86-64
        file sortgrcd | grep x86-64
        file makdbs | grep x86-64

  build-aarch64:
    name: Linux aarch64
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      uses: uraimo/run-on-arch-action@v2
      with:
        arch: aarch64
        distro: ubuntu22.04
        githubToken: ${{ github.token }}
        dockerRunArgs: |
          --volume "${PWD}:/spaln"
        install: |
          apt-get update -q -y
          apt-get install -q -y make g++-10 zlib1g-dev file
        run: |
          set -x
          cd /spaln/src
          ./configure
          make -j CXX=g++-10 
          file spaln | grep aarch64
          file makmdm | grep aarch64
          file sortgrcd | grep aarch64
          file makdbs | grep aarch64